// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package MyGame

///union Any { Monster, Weapon, Pickup }
type Any = byte
const (
	AnyNONE Any = 0
	AnyMonster Any = 1
	AnyWeapon Any = 2
)

var EnumNamesAny = map[Any]string{
	AnyNONE:"NONE",
	AnyMonster:"Monster",
	AnyWeapon:"Weapon",
}

