// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package MyGame

type Color = int8
const (
	ColorRed Color = 1
	ColorGreen Color = 2
	ColorBlue Color = 3
)

var EnumNamesColor = map[Color]string{
	ColorRed:"Red",
	ColorGreen:"Green",
	ColorBlue:"Blue",
}

